### PR TITLE
Real Time object detection on mobile networks

### PR DESCRIPTION
**Pull request by mariemloukill**

### CODE REVIEW

**Comment by mariemloukill** [comment]
pull request

**Comment by seakkas** [comment]
Hi Mariem,

Could you update the README file in the report folder?

And the main README file should be like a blog post. It should be a summary of your work. For instance: https://ai.googleblog.com/2018/04/mobilenetv2-next-generation-of-on.html

**Comment by mariemloukill** [comment]
updated readme files

**Comment by seakkas** [comment]
It is merged now. Good job!

**Pull request merged**
