### PR TITLE
Group 4

### PR DESCRIPTION
**Pull request by ManjeetKP**

### CODE REVIEW

**Comment by seakkas** [comment]
Good job!

I found a few simple issues:

1. Could you remove my texts from README files? For instance: "Describe here who did what in the project or report."
2. Some images are not visible in the blog post. Could you fix them?

**Comment by ManjeetKP** [comment]
Sure, Let us fix it and update.

**Comment by ManjeetKP** [comment]
It's been fixed, now do we need to raise a new pull request?

**Comment by seakkas** [comment]
It is merged now. No need to pull request.

**Comment by ManjeetKP** [comment]
thank you

**Pull request merged**
